[package]
name = "web3"
version = "0.0.1"
description = "Ethereum JSON-RPC client."
authors = ["Tomasz Drwięga <tomasz@ethcore.io>"]
build = "build.rs"

[dependencies]
futures = "0.1"
jsonrpc-core = { git = "https://github.com/ethcore/jsonrpc" }
log = "0.3"
rustc-serialize = "0.3"
serde = "0.8"
serde_json = "0.8"
# Optional deps
reqwest = { version = "0.2", optional = true }
serde_derive = { version = "0.8", optional = true }

[dev-dependencies]
# For examples
tokio-core = "0.1"
futures-cpupool = "0.1"

[build-dependencies]
serde_codegen = { version = "0.8", optional = true }

[features]
default = ["http", "serde_codegen"]
nightly = ["serde_derive"]
http = ["reqwest"]
